run:
  timeout: "5m"

linters-settings:
  lll:
    line-length: 110

linters:
  enable:
    - lll
    - gocritic
    - misspell
    - gosec
    - unconvert
    - prealloc
    - nakedret
    - importas
    - gci
    - godot
    - revive

issues:
  include:
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015
